typography/typography/typography/apps/main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('pay', views.pay, name = 'pay'),
	path('contacts', views.contacts, name = 'contacts'),
	path('writeus', views.writeus, name = 'writeus'),
	path('registration', views.registration, name='registration')
]

typography/typography/typography/apps/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
	path('', views.orders, name = 'orders'),
	path('<int:order_id>/', views.orderdetail, name = 'orderdetail'),
	path('neworder/<int:service_id>', views.neworder, name = 'neworder'),
	path('newmes/<int:order_id>/', views.newmessage, name = 'newmessage'),
	path('newimg/<int:order_id>/', views.upload_pic, name='upload_pic'),
]

typography/typography/typography/apps/services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('sales', views.sales, name = 'sales'),
	path('reviews', views.reviews, name = 'reviews'),
	path('newreview', views.newreview, name = 'newreview'),
	path('<int:service_id>/', views.servicedetail, name = 'servicedetail'),
	path('sales/<int:sale_id>', views.saledetail, name = "saledetail"),
	
]

typography/typography/typography/apps/users/urls.py
from django.urls import path

from . import views

app_name='users'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('workers/<int:worker_id>/', views.workerdetail, name = 'workerdetail'),
]

typography/typography/typography/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
	path('orders/', include('orders.urls')),
	path('services/', include('services.urls')),
	path('', include('main.urls')),
	path('workers/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

typography/typography/typography/apps/orders/models.py
from django.db import models

from users.models import Client, Worker
from services.models import Service
#Proverit` logichno li rasstavlenni spiski!
class Order(models.Model):
	order_date = models.DateTimeField('Дата заказа')
	order_client = models.ForeignKey(Client, on_delete = models.CASCADE, null=True, blank=True)
	order_name = models.CharField('Имя(если не зарегстрирован)', max_length = 50, null = True, blank = True)
	order_email = models.CharField('E-mail(если не зарегстрирован)', max_length = 50, null = True, blank = True)
	order_telephonenumber = models.CharField('Телефон(если не зарегстрирован)', max_length = 50, null = True, blank = True)
	order_state = models.CharField('Статус заказа', max_length = 100)
	order_service = models.ForeignKey(Service, on_delete = models.CASCADE)
	order_price = models.FloatField('Стоимость заказа')
	order_payed = models.FloatField('Оплачено')
	order_worker = models.ManyToManyField(Worker)
	order_count = models.BigIntegerField('Количество')
	order_comment = models.TextField('Комментарий')
	order_image = models.FileField('Дизайн')	

	class Meta:
		verbose_name = 'Заказ'
		verbose_name_plural = 'Заказы'

class OrderChatMessage(models.Model):
	message_date = models.DateTimeField('Дата сообщения')
	message_author = models.CharField('Автор', max_length=100)
	message_order = models.ForeignKey(Order, on_delete = models.CASCADE)
	message_text = models.TextField('Текст сообщения')
	message_image = models.FileField('Картинка', null=True, blank=True)


	class Meta:
		verbose_name = 'Сообщение'
		verbose_name_plural = 'Сообщения'

class Review(models.Model):
	review_pubdate = models.DateTimeField('Дата публикации')
	review_service = models.ForeignKey(Service, on_delete = models.CASCADE)
	review_worker = models.ForeignKey(Worker, on_delete = models.CASCADE)
	review_client = models.ForeignKey(Client, on_delete = models.CASCADE, null = True, blank = True)
	review_name = models.CharField('Имя(если не зарегстрирован)', max_length = 50, null = True, blank = True)
	review_telephonenumber = models.CharField('Номер телефона', max_length = 11)
	review_email = models.EmailField('E-mail')
	review_text = models.TextField('Текст отзыва')
	review_screenshot = models.FileField('Скриншот')
	class Meta:
		verbose_name = 'Отзыв'
		verbose_name_plural = 'Отзывы'		

class ReviewAnswer(models.Model):
	reviewanswer_author = models.ForeignKey(Worker, on_delete = models.CASCADE)
	reviewanswer_review = models.ForeignKey(Review, on_delete = models.CASCADE)
	reviewanswer_text = models.TextField('Текст')

	class Meta:
		verbose_name = 'Ответ'
		verbose_name_plural = 'Ответы'	

typography/typography/typography/apps/orders/forms.py
from django import forms


class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

typography/typography/typography/apps/main/views.py
from django.shortcuts import render, redirect
from services.models import *
from orders.models import *
from django.http import HttpResponse, HttpResponseRedirect # Add this
from .forms import ContactForm # Add this
from django.core.mail import *
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.contrib.auth.models import User, Group
# Create your views here.
def index(request):
	last_sales_list = Sale.objects.order_by('id')[:3]
	last_reviews_list = Review.objects.order_by('id')[:3]
	return render(request, 'main/lists.html', {'last_sales_list':last_sales_list, 'last_reviews_list':last_reviews_list})

def writeus(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			sender_name = form.cleaned_data['name']
			sender_email = form.cleaned_data['email']

			message = "{0} has sent you a new message:\n\n{1}".format(sender_name, form.cleaned_data['message'])
			send_mail('New Enquiry', message, sender_email, ['example@example.com'])
			return render(request, 'main/writeusanswer.html')
	else:
		form = ContactForm()

			#send email code goes here
	return render(request, 'main/writeus.html', {'form':form})

def registration(request):
	if request.method == 'POST':
		name = request.POST.get('name')
		email = request.POST.get('email')
		password = request.POST.get('password')
		newuser = User.objects.create_user(username = name, email = email, password = password)
		newuser.save()
		return HttpResponseRedirect('/accounts/login')
	return render(request, 'main/registration.html')	

def pay(request):
	return render(request, 'main/payment.html')

def contacts(request):
	return render(request, 'main/contacts.html')

typography/typography/typography/apps/orders/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import datetime
from django.utils import timezone
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from users.models import *
from orders.models import *
from django.contrib.auth.models import User, Group
from .forms import ImageUploadForm 

def orders(request):
	services_list = Service.objects.all()
	defaultdatestart = datetime.datetime.today() - relativedelta(years= 1)
	defaultdateend = datetime.datetime.today()
	client_list = Client.objects.all()

	if request.user.username == 'admin':
		return HttpResponseRedirect('/admin/orders/')
	if request.user.is_authenticated:
		try:
			client = Client.objects.get(user = request.user)
			order_list = client.order_set.all()
			ascordesc = request.GET.get('ascordesc', 'Сначала дешевые')
			orderby = '-order_price'
			service = request.GET.get('service', 'Не выбрано')
			ID = request.GET.get('ID', '')
			if ascordesc == 'Сначала дорогие':
				orderby = orderby
			else:
				orderby = 'order_price'
			if defaultdatestart and defaultdateend:
				order_list = client.order_set.filter(order_date__range = (defaultdatestart, defaultdateend))
			if service != 'Не выбрано':
				order_list = client.order_set.filter(order_service__service_name = service, order_date__range = (defaultdatestart, defaultdateend)).order_by(orderby)
			elif ID != '':
				order_list = client.order_set.filter(id = ID)
			return render(request, 'orders/profile.html', {'order_list':order_list, 'client':client, 'services_list':services_list, 'defaultdatestart':defaultdatestart, 'defaultdateend':defaultdateend})			
	# elif request.user.is_authenticated:
		except:
			worker = Worker.objects.get(user = request.user)
			order_list = worker.order_set.all()
			ascordesc = request.GET.get('ascordesc', 'Сначала дешевые')
			orderby = '-order_price'
			service = request.GET.get('service', 'Не выбрано')
			client = request.GET.get('client', 'Не выбрано')
			ID = request.GET.get('ID', '')
			if ascordesc == 'Сначала дорогие':
				orderby = orderby
			else:
				orderby = 'order_price'
			if defaultdatestart and defaultdateend:
				order_list = worker.order_set.filter(order_date__range = (defaultdatestart, defaultdateend))
			if service != 'Не выбрано':
				order_list = worker.order_set.filter(order_service__service_name = service, order_date__range = (defaultdatestart, defaultdateend)).order_by(orderby)
			elif service != 'Не выбрано' and client != 'Не выбрано':
				order_list = worker.order_set.filter(order_service__service_name = service, order_date__range = (defaultdatestart, defaultdateend), order_client__client_name = client).order_by(orderby)
			elif client != 'Не выбрано':
				order_list = worker.order_set.filter(order_client__client_name = client, order_date__range = (defaultdatestart, defaultdateend)).order_by(orderby)
			elif ID != '':
				order_list = worker.order_set.filter(id = ID)
			return render(request, 'orders/profileworker.html', {'order_list':order_list, 'worker':worker, 'client_list':client_list, 'services_list':services_list, 'defaultdatestart':defaultdatestart, 'defaultdateend':defaultdateend})

	else:
		return HttpResponseRedirect('/accounts/login')

def orderdetail(request, order_id):
	#try: 		
	o = Order.objects.get( id = order_id )
	messages = OrderChatMessage.objects.filter(message_order = o)
	worker_list = o.order_worker
	service = o.order_service
	amount = o.order_price - o.order_payed		
	return render(request, 'orders/order.html', {'o':o, 'amount':amount, 'worker_list':worker_list, 'service':service, 'messages':messages})
	#except:
		#raise Http404("Заказ не найден!")

def neworder(request, service_id):
	if request.user.is_authenticated:
		try:
			if request.user.client:
				service = Service.objects.get( id = service_id)
				if request.method == 'POST':
					client = Client.objects.get(user = request.user)
					service = Service.objects.get( id = service_id)
					worker_list = Worker.objects.filter( worker_printtype = service.service_printtype)
					date = datetime.datetime.today()
					state = "обработка"
					count = request.POST.get('count', '')
					price = service.service_price * int(count)
					payed = 0
					comment = ''
					image = service.service_image
					neworder = Order.objects.create(order_date = date, order_client = client, order_state = state, order_service = service, order_price = price, order_payed = payed, order_count = count, order_comment = comment, order_image = image)
					neworder.save()
					return HttpResponseRedirect('/orders')
				return render(request, 'orders/neworder.html', {'s':service})
		except:
			service = Service.objects.get( id = service_id )
			if request.method == 'POST':
				name = request.POST.get('name')
				email = request.POST.get('email')
				telnum = request.POST.get('telnum')
				service = Service.objects.get( id = service_id)
				worker_list = Worker.objects.filter( worker_printtype = service.service_printtype)
				date = datetime.datetime.today()
				state = "обработка"
				count = request.POST.get('count', '')
				price = service.service_price * int(count)
				payed = 0
				comment = ''
				image = service.service_image
				neworder = Order.objects.create(order_date = date, order_name = name, order_telephonenumber = telnum, order_email = email, order_state = state, order_service = service, order_price = price, order_payed = payed, order_count = count, order_comment = comment, order_image = image)
				neworder.save()
				return render(request, 'orders/unreganswer.html', {'s':service})
			return render(request, 'orders/neworderunregistered.html', {'s':service})
	else:
		service = Service.objects.get( id = service_id )
		if request.method == 'POST':
			name = request.POST.get('name')
			email = request.POST.get('email')
			telnum = request.POST.get('telnum')
			service = Service.objects.get( id = service_id)
			worker_list = Worker.objects.filter( worker_printtype = service.service_printtype)
			date = datetime.datetime.today()
			state = "обработка"
			count = request.POST.get('count', '')
			price = service.service_price * int(count)
			payed = 0
			comment = ''
			image = service.service_image
			neworder = Order.objects.create(order_date = date, order_name = name, order_telephonenumber = telnum, order_email = email, order_state = state, order_service = service, order_price = price, order_payed = payed, order_count = count, order_comment = comment, order_image = image)
			neworder.save()
			return render(request, 'orders/unreganswer.html', {'s':service})
		return render(request, 'orders/neworderunregistered.html', {'s':service})

def newmessage(request, order_id): #date author order text
	if request.method == 'POST':
		order = Order.objects.get(id = order_id)
		date = datetime.datetime.today()
		author = ""
		text = request.POST.get('text')
		try:
			author = request.user.client.client_name
		except:
			author = request.user.worker.worker_name
		message = OrderChatMessage.objects.create(message_date = date, message_order = order, message_author = author, message_text = text)
		message.save()
		return HttpResponseRedirect('/orders/'+ str(order.id))
		#return HttpResponseRedirect('/orders/{order.id}')
	else:
		return HttpResponseRedirect('/orders/'+ str(order.id))
	return HttpResponseRedirect('/orders/'+ str(order.id))
	# order_date = models.DateTimeField('Дата заказа')
	# order_client = models.ForeignKey(Client, on_delete = models.CASCADE)
	# order_state = models.CharField('Статус заказа', max_length = 100)
	# order_service = models.ForeignKey(Service, on_delete = models.CASCADE)
	# order_price = models.FloatField('Стоимость заказа')
	# order_payed = models.FloatField('Оплачено')
	# order_worker = models.ManyToManyField(Worker)
	# order_count = models.BigIntegerField('Количество')
	# order_comment = models.TextField('Комментарий')
	# order_image = models.FileField('Дизайн')	

def upload_pic(request, order_id):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            m = Order.objects.get(id = order_id)
            m.order_image = form.cleaned_data['image']
            message = OrderChatMessage.objects.create(message_date = datetime.datetime.today(), message_author = 'author', message_order = m, message_text = 'картинка', message_image = m.order_image )
            message.save()
            m.save()
            return HttpResponseRedirect('/orders/'+ str(m.id))
    return HttpResponseForbidden('allowed only via POST')

typography/typography/typography/apps/users/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import datetime
from django.utils import timezone
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from users.models import *
from orders.models import *
from django.contrib.auth.models import User, Group 
from django.core.paginator import *
# Create your views here.
def index(request):
	workers_list = Worker.objects.all()
	paginator = Paginator(workers_list, 3)
	try:
		page = int(request.GET.get('page', 1))
	except:
		page = 1
	try:
		workers = paginator.page(page)
	except(EmptyPage, InvalidPage):
		workers = paginator.page(paginator.num_pages)
	return render(request, 'users/list.html', {'workers_list':workers_list, 'workers':workers})


def workerdetail(request, worker_id):
	services_list = Service.objects.all()
	defaultdatestart = datetime.datetime.today() - relativedelta(years= 1)
	defaultdateend = datetime.datetime.today()
	client_list = Client.objects.all()
	worker = Worker.objects.get(id = worker_id)
	order_list = worker.order_set.all()
	ascordesc = request.GET.get('ascordesc', 'Сначала дешевые')
	orderby = '-order_price'
	service = request.GET.get('service', 'Не выбрано')
	client = request.GET.get('client', 'Не выбрано')
	ID = request.GET.get('ID', '')
	sumprice = 0
	if ascordesc == 'Сначала дорогие':
		orderby = orderby
	else:
		orderby = 'order_price'
	if defaultdatestart and defaultdateend:
		order_list = worker.order_set.filter(order_date__range = (defaultdatestart, defaultdateend))
	if service != 'Не выбрано':
		order_list = worker.order_set.filter(order_service__service_name = service, order_date__range = (defaultdatestart, defaultdateend)).order_by(orderby)
	elif service != 'Не выбрано' and client != 'Не выбрано':
		order_list = worker.order_set.filter(order_service__service_name = service, order_date__range = (defaultdatestart, defaultdateend), order_client__client_name = client).order_by(orderby)
	elif client != 'Не выбрано':
		order_list = worker.order_set.filter(order_client__client_name = client, order_date__range = (defaultdatestart, defaultdateend)).order_by(orderby)
	elif ID != '':
		order_list = worker.order_set.filter(id = ID)
	for o in order_list:
		sumprice = sumprice + o.order_price
	return render(request, 'users/workerdetail.html', {'sumprice':sumprice, 'order_list':order_list, 'worker':worker, 'client_list':client_list, 'services_list':services_list, 'defaultdatestart':defaultdatestart, 'defaultdateend':defaultdateend})

typography/typography/typography/templates/users/list.html
{% extends 'workers.html' %}

{% block workerscontent %}

	{% if workers_list %}
	
		{% for s in workers.object_list %}
					<div class="card_container">
					  <img src="{{s.worker_image.url}}" alt="Avatar" class="card_imag">
					  <div class="vertical-line"/></div>
					  <p><span>{{s.worker_name}}</span></p>					  
					  	<p>{% for p in s.worker_service.all %}
							<p>{{p}}</p>
							{% endfor %}
					  	</p>
					  	{% if user.worker %}
						<a href="{% url 'users:workerdetail' s.id %}"><button class='more'>Подробнее</button></a>
						{% endif %}	
					</div>
		{% endfor %}

	{% else %}
		Сервисов нету=(
	{% endif %}

{% endblock %}		
		
{% block pagination %}		
	<div class="pagination">

			{% if workers.has_previous %}
				<a href="?page={{workers.previous_page_number}}">Назад</a>
			{% endif %}
			{% for pg in workers.paginator.page_range %}
				{% if workers.number == pg %}
				<a class="active" href="?page={{pg}}">{{pg}}</a>				
				{% else %}
				<a href="?page={{pg}}">{{pg}}</a>
				{% endif %}
			{% endfor %}
			{% if workers.has_next %}
				<a href="?page={{workers.next_page_number}}">Далее</a>
			{% endif %}
	</div>
{% endblock %}

typography/typography/typography/templates/users/workerdetail.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="ru">

<head>
	<meta charset="UTF-8" content="width=device-width, initial-scale=1">
	<title>Профиль</title>
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet"> 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
	<header>
		<div class="mainheader">
			<div class="logo">				
				<img src="{% static 'img/newspaper.png' %}" alt="">
				<p><a href="">Типография на Ленина</a></p>					 
			</div>
			<div class="contacts">
				<div class="phone"><img src="{% static 'img/phone.png' %}" alt="">
				88005553535</div>
				<div class="loc"><img src="{% static 'img/location.png' %}" alt="">
				Ул. Ленина, д.11</div>
				
			</div>
			<div class="social">

				<div class="vk">
    				<a href="#" target="_blank"><i class="fa fa-vk fa-2x"></i></a> 
				</div>
				<div class="odnoklassniki">
    				<a href="#" target="_blank"><i class="fa fa-odnoklassniki fa-2x"></i></a>
				</div>
				<div class="facebook">
    				<a href="#" target="_blank"><i class="fa fa-facebook fa-2x"></i></a>    
				</div>
				<div class="instagram">
    				<a href="#" target="_blank"><i class="fa fa-instagram fa-2x"></i></a>
				</div>
			</div>
			<div class="login">
				<img src="{% static 'img/user.png' %}" alt="">
				{% if user.is_authenticated %}
				<p><a href="#">{{user.username}}</a></p>
				<a href="{% url 'logout' %}"><button class="loginbutton" type="button">Выйти</button></a>
				{% else %}
				<p><a href="{% url 'login' %}">Гость</a></p>
				<a href="{% url 'login' %}"><button class="loginbutton" type="button">Войти</button></a>
				{% endif %}
			</div>
		</div>
	</header>
	<div class="content prflcnt">
	<div class="topnav" id="myTopnav">
		  <a href="{% url 'main:index' %}">Главная</a>
		  <a href="{% url 'services:index' %}" class="activem">Каталог</a>
		  <a href="{% url 'services:sales' %}">Акции</a>
		  <a href="{% url 'main:pay' %}">Оплата</a>
		  <a href="{% url 'services:reviews' %}">Отзывы</a>
		  <a href="{% url 'main:contacts' %}">Контакты</a>
		  <a href="{% url 'users:index' %}">Работники</a>
		  <a href="{% url 'orders:orders' %}">Заказы</a>
	  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
	    <i class="fa fa-bars"></i>
	  </a>
	</div>
	<ul class="breadcrumb">
	  <li><a href="{% url 'main:index' %}">Главная</a></li>
	  <li><a href="{% url 'users:index' %}">Работники</a></li>
	  <li class="activem">{{worker.worker_name}}</li>
	</ul>
	<div class="catalogtitle"><h1>{{worker.worker_name}}</h1></div>
	<div class="tabs">
		    <input type="radio" name="inset" value="" id="tab_1" checked>
		    <label for="tab_1">Аналитика</label>

		   
		    <div id="txt_1">
		        <div class="information">
				 	<fieldset>
				 		<legend>Оснонвные сведения</legend>
				 		<div class="fieldcontent">				 		
				 		<p>ФИО:<label for="">{{worker.worker_name}}</label></p>
				 		<p>Дата рождения:<label for="">{{worker.worker_birthdaydate}}</label></p>
				 		<p>Номер телефона:<label for="">{{worker.worker_telephonenumber}}</label></p>
				 		<p>e-mail:<label for="">{{worker.worker_email}}</label></p>
				 		<!-- <div class="chlogbtn"><button>Смена логина</button></div> -->
				 		</div>
					</fieldset>
	 			</div>
	 			<div class="filtersearch">
				 	<fieldset>
				 		<legend>Фильтр и поиск <a href="#" class="hide">(скрыть)</a><a href="#" class="show">(показать)</a></legend>
				 		<div class="inp">
				 			<form action="{% url 'users:workerdetail' worker.id %}">
					<input type="date" name="defaultdatestart" value={{defaultdatestart.date|date:"Y-m-d"}}>
					<span>-</span>
					<input type="date" name="defaultdateend" value={{defaultdateend.date|date:"Y-m-d"}}>	
					<input type="text" name="ID" placeholder="ID">
					</div>
					<div class="sel">
					<select value="Не выбрано" name="service">
						<option>Не выбрано</option>
					 {% for s in services_list %}
					  <option>{{s.service_name}}</option>
					  {% endfor %}
					</select>
					<select value="Не выбрано" name="client">
						<option>Не выбрано</option>
					 {% for c in client_list %}
					  <option>{{c.client_name}}</option>
					  {% endfor %}
					</select>
					<select name="ascordesc">
						<option>Сначала дешевые</option>
					  <option>Сначала дорогие</option>
					  		  
					</select>
					</div>
					<div class="findbtn"><button type="submit">Найти</button></div>
					</form>
					</fieldset>
	 			</div>
	 			<h2 align="center" id="summ">Итого заработано: {{sumprice}} руб.</h2>
	 			<div class="ordercards">
	 				{% if worker.order_set.all %}
	 						{% for o in order_list %}
								<div class="card_container">
								  <img src="{{o.order_image.url}}" alt="Avatar" class="card_imag">
								  <div class="vertical-line"/></div>
								  <p><span>{{o.order_service.service_name}}({{o.order_client.client_name}})</span></p>
								  <p>Последняя активность: {{o.order_date.date|date:"Y-m-d"}}
								  </p>
								  <p>Статус: {{o.order_state}}</p>
								  <p>Стоимоть: {{o.order_price}} руб.</p>
								  <p>Количество: {{o.order_count}} шт.</p>							  
								 <!--  <button class='del'>Удалить</button> -->
								  <a href="{% url 'orders:orderdetail' o.id %}"><button class='more'>Подробнее</button></a>
								</div> 
							{% endfor %}
					{% else %}
						Zakazov net=(
					{% endif %}
		    	</div>
				

	 		</div>

		    </div>
		</div>
	</div>
	<footer>
		<div class="mainfooter">
			<div class="logo">
				<img src="{% static 'img/newspaper.png'%}" alt="">
				<p>Типография на Ленина</p>
			</div>
			<div class="contacts">
				<div class="phone"><img src="{% static 'img/phone.png' %}" alt="">
				88005553535</div>
				<div class="loc"><img src="{% static 'img/location.png' %}" alt="">
				Ул. Ленина, д.11</div>
			</div>
				
			<div class="social">
				<div class="vk">
    				<a href="#" target="_blank"><i class="fa fa-vk fa-2x"></i></a> 
				</div>
				<div class="odnoklassniki">
    				<a href="#" target="_blank"><i class="fa fa-odnoklassniki fa-2x"></i></a>
				</div>
				<div class="facebook">
    				<a href="#" target="_blank"><i class="fa fa-facebook fa-2x"></i></a>    
				</div>
				<div class="instagram">
    				<a href="#" target="_blank"><i class="fa fa-instagram fa-2x"></i></a>
				</div>
			</div>
		</div>
	</footer>
 <script>
function myFunction() {
    var x = document.getElementById("myTopnav");
    if (x.className === "topnav") {
        x.className += " responsive";
    } else {
        x.className = "topnav";
    }
}
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script>
$(document).ready(function(){
  $(".filtersearch .hide").click(function(){
	$(".hide").toggle()
	$(".show").css('display', 'inline-block')
    $("fieldset input,fieldset select,fieldset button, fieldset span").hide();
  });
});
$(document).ready(function(){
  $(".filtersearch .show").click(function(){
	$(".show").toggle()
	$(".hide").toggle()
    $("fieldset input,fieldset select,fieldset button, fieldset span").show();
  });
});
</script>
</body>

</html>